import { Inter } from "next/font/google";
import "./globals.css";
import 'react-toastify/dist/ReactToastify.css';
  
import CustomNavbar from '../components/CustomNavbar'

import { ToastContainer } from 'react-toastify';
import { UserProvider } from "@/contexts/userContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <UserProvider>

          <ToastContainer/>
          <CustomNavbar />
          <div className="mt-0">{children}</div>

        </UserProvider>
      </body>
    </html>
  );
}
